- hosts: master02.ovh.binarium.ca
  tasks:
    - name: Transfer SSL Certs
      synchronize:
        src: /etc/letsencrypt
        dest: can-mtl-pbx01.cloudserv.binarium.ca:/etc/
        mode: push
      delegate_to: master02.ovh.binarium.ca
