- hosts: master02.ovh.binarium.ca
  tasks:
    - name: Transfer SSL Certs
      synchronize:
        src: /etc/letsencrypt
        dest: rsync://can-mtl-pbx01.cloudserv.binarium.ca/etc/letsencrypt
        dest_port: 9022
        mode: push
