- hosts: SSLCertHosts
  tasks:
    - name: Transfer SSL Certs
#      command: bash /usr/local/bin/copySSL.sh
      command:  /usr/bin/rsync -e "ssh -p 9022" -arvvvvz  www4.binarium.ca:/etc/letsencrypt /etc/
