- hosts: master02.ovh.binarium.ca
  tasks:
    - name: Transfer SSL Certs
      synchronize:
        src: /etc/letsencrypt
        dest: /etc/letsencrypt
        mode: push
      delegate_to: can-mtl-pbx01.cloudserv.binarium.ca
